name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and test
      run: xcodebuild clean build test -project Contact_POC.xcodeproj -scheme "CI" CODE_SIGNING_IDENTITY="Apple Development" CODE_SIGNING_REQUIRED=YES