name: Swift

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and test
      run: xcodebuild clean test -project Contact_POC.xcodeproj -scheme "CI" -destination 'platform=iOS Simulator,name=iPhone 13 Pro,OS=15.2' CODE_SIGNING_IDENTITY="Apple Development" CODE_SIGNING_REQUIRED=YES